[2024-04-16T12:08:55.611+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-16T12:08:55.683+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_data_dag.write_to_csv scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-16T12:08:55.712+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_data_dag.write_to_csv scheduled__2024-04-15T00:00:00+00:00 [queued]>
[2024-04-16T12:08:55.713+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-16T12:08:55.778+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): write_to_csv> on 2024-04-15 00:00:00+00:00
[2024-04-16T12:08:55.807+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=50) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-16T12:08:55.811+0000] {standard_task_runner.py:63} INFO - Started process 55 to run task
[2024-04-16T12:08:55.817+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'get_data_dag', 'write_to_csv', 'scheduled__2024-04-15T00:00:00+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/get_data_dag.py', '--cfg-path', '/tmp/tmp3talvffv']
[2024-04-16T12:08:55.819+0000] {standard_task_runner.py:91} INFO - Job 85: Subtask write_to_csv
[2024-04-16T12:08:55.997+0000] {task_command.py:426} INFO - Running <TaskInstance: get_data_dag.write_to_csv scheduled__2024-04-15T00:00:00+00:00 [running]> on host 838671e3e35b
[2024-04-16T12:08:56.182+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yazid' AIRFLOW_CTX_DAG_ID='get_data_dag' AIRFLOW_CTX_TASK_ID='write_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-04-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-15T00:00:00+00:00'
[2024-04-16T12:08:56.187+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-16T12:08:56.189+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-16T12:08:56.191+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: write_to_csv() missing 1 required positional argument: 'data'
[2024-04-16T12:08:56.215+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=get_data_dag, task_id=write_to_csv, execution_date=20240415T000000, start_date=20240416T120855, end_date=20240416T120856
[2024-04-16T12:08:56.260+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 85 for task write_to_csv (write_to_csv() missing 1 required positional argument: 'data'; 55)
[2024-04-16T12:08:56.297+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-16T12:08:56.369+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-16T12:08:56.374+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
