[2024-04-15T14:54:25.889+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T14:54:25.991+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_data_dag.write_to_txt scheduled__2024-04-12T00:00:00+00:00 [queued]>
[2024-04-15T14:54:26.013+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_data_dag.write_to_txt scheduled__2024-04-12T00:00:00+00:00 [queued]>
[2024-04-15T14:54:26.016+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 6
[2024-04-15T14:54:26.047+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): write_to_txt> on 2024-04-12 00:00:00+00:00
[2024-04-15T14:54:26.083+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'get_data_dag', 'write_to_txt', 'scheduled__2024-04-12T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/get_data_dag.py', '--cfg-path', '/tmp/tmpw888uc5l']
[2024-04-15T14:54:26.096+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask write_to_txt
[2024-04-15T14:54:26.087+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=753) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T14:54:26.105+0000] {standard_task_runner.py:63} INFO - Started process 762 to run task
[2024-04-15T14:54:26.365+0000] {task_command.py:426} INFO - Running <TaskInstance: get_data_dag.write_to_txt scheduled__2024-04-12T00:00:00+00:00 [running]> on host ead826da457c
[2024-04-15T14:54:26.615+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yazid' AIRFLOW_CTX_DAG_ID='get_data_dag' AIRFLOW_CTX_TASK_ID='write_to_txt' AIRFLOW_CTX_EXECUTION_DATE='2024-04-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-12T00:00:00+00:00'
[2024-04-15T14:54:26.618+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T14:54:26.621+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T14:54:26.621+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: write_to_txt() missing 1 required positional argument: 'data'
[2024-04-15T14:54:26.639+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=get_data_dag, task_id=write_to_txt, execution_date=20240412T000000, start_date=20240415T145425, end_date=20240415T145426
[2024-04-15T14:54:26.671+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task write_to_txt (write_to_txt() missing 1 required positional argument: 'data'; 762)
[2024-04-15T14:54:26.732+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-15T14:54:26.782+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-15T14:54:26.790+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
