[2024-04-15T14:48:09.119+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T14:48:09.152+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: calculator_dag.generate_random_numbers scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T14:48:09.163+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: calculator_dag.generate_random_numbers scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T14:48:09.164+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-15T14:48:09.184+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): generate_random_numbers> on 2024-04-14 00:00:00+00:00
[2024-04-15T14:48:09.198+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=639) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T14:48:09.201+0000] {standard_task_runner.py:63} INFO - Started process 641 to run task
[2024-04-15T14:48:09.199+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'calculator_dag', 'generate_random_numbers', 'scheduled__2024-04-14T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/calculator_dag.py', '--cfg-path', '/tmp/tmpq9pwxpku']
[2024-04-15T14:48:09.202+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask generate_random_numbers
[2024-04-15T14:48:09.261+0000] {task_command.py:426} INFO - Running <TaskInstance: calculator_dag.generate_random_numbers scheduled__2024-04-14T00:00:00+00:00 [running]> on host ead826da457c
[2024-04-15T14:48:09.348+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yazid' AIRFLOW_CTX_DAG_ID='calculator_dag' AIRFLOW_CTX_TASK_ID='generate_random_numbers' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T00:00:00+00:00'
[2024-04-15T14:48:09.350+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T14:48:09.351+0000] {python.py:237} INFO - Done. Returned value was: [5, 17, 23, 34, 23, 50, 4, 34, 30, 30, 31, 19, 34, 12, 19, 3, 19, 47, 17, 17, 45, 1, 14, 47, 47]
[2024-04-15T14:48:09.351+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T14:48:09.372+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=calculator_dag, task_id=generate_random_numbers, execution_date=20240414T000000, start_date=20240415T144809, end_date=20240415T144809
[2024-04-15T14:48:09.419+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-15T14:48:09.447+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-04-15T14:48:09.449+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
