[2024-04-15T15:30:30.319+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-15T15:30:30.446+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_airflow_dag.echo_hello_airflow scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T15:30:30.466+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_airflow_dag.echo_hello_airflow scheduled__2024-04-14T00:00:00+00:00 [queued]>
[2024-04-15T15:30:30.477+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 6
[2024-04-15T15:30:30.510+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): echo_hello_airflow> on 2024-04-14 00:00:00+00:00
[2024-04-15T15:30:30.525+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1088) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-15T15:30:30.527+0000] {standard_task_runner.py:63} INFO - Started process 1097 to run task
[2024-04-15T15:30:30.527+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hello_***_dag', 'echo_hello_***', 'scheduled__2024-04-14T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/hello_***_dag.py', '--cfg-path', '/tmp/tmpwpw0e_6q']
[2024-04-15T15:30:30.530+0000] {standard_task_runner.py:91} INFO - Job 38: Subtask echo_hello_***
[2024-04-15T15:30:30.622+0000] {task_command.py:426} INFO - Running <TaskInstance: hello_airflow_dag.echo_hello_airflow scheduled__2024-04-14T00:00:00+00:00 [running]> on host ead826da457c
[2024-04-15T15:30:30.844+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='yazid' AIRFLOW_CTX_DAG_ID='hello_***_dag' AIRFLOW_CTX_TASK_ID='echo_hello_***' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-14T00:00:00+00:00'
[2024-04-15T15:30:30.849+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-15T15:30:30.860+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-15T15:30:30.870+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello ***']
[2024-04-15T15:30:30.913+0000] {subprocess.py:86} INFO - Output:
[2024-04-15T15:30:30.941+0000] {subprocess.py:93} INFO - hello ***
[2024-04-15T15:30:30.945+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-15T15:30:30.947+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-15T15:30:30.999+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=hello_***_dag, task_id=echo_hello_***, execution_date=20240414T000000, start_date=20240415T153030, end_date=20240415T153030
[2024-04-15T15:30:31.071+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-15T15:30:31.130+0000] {taskinstance.py:3482} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-04-15T15:30:31.135+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
